version: 0.0
os: linux 
files:
  - source: /
    destination: /var/www/skolera/skolera-angular/
permissions:
  - object : /var/www/skolera/skolera-angular/
    owner: root
    group: root
    mode:  777
hooks:    
    AfterInstall:
    - location: build_script.sh

